pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'ilv2' // если другой username на DockerHub, напиши мне
    }

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t flask-app:latest ./task_5'
            }
        }

        stage('Test') {
            steps {
                echo 'No unit tests provided'
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKERHUB_TOKEN')]) {
                    sh "echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin"
                    sh "docker tag flask-app:latest $DOCKERHUB_USER/flask-app:latest"
                    sh "docker push $DOCKERHUB_USER/flask-app:latest"
                }
            }
        }

        stage('Helm Deploy') {
            steps {
                sh 'helm upgrade --install flask-app ./task_5/flask-app'
            }
        }

        stage('Verify App') {
            steps {
                sh 'curl --fail http://flask-app.default.svc.cluster.local:8080 || echo \"Verification failed\"'
            }
        }
    }

    post {
        success {
            mail to: 'iliyeva.aziza02@mail.ru',
                 subject: "✅ Jenkins Pipeline SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "The pipeline for ${env.JOB_NAME} #${env.BUILD_NUMBER} completed successfully. Check details at ${env.BUILD_URL}"
        }
        failure {
            mail to: 'iliyeva.aziza02@mail.ru',
                 subject: "❌ Jenkins Pipeline FAILURE: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "The pipeline for ${env.JOB_NAME} #${env.BUILD_NUMBER} failed. Check details at ${env.BUILD_URL}"
        }
    }
}
