sonar.projectKey=flask-app
sonar.projectName=Flask App
sonar.sources=../task_5
sonar.language=py
sonar.python.version=3
sonar.host.url=http://localhost:9000
sonar.login=sqa_dc04046fc4a2f17c0dcc3e95e0efa75098113fd6
