name: Terraform CI/CD

on:
  push:
    branches: [main, task_1]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2
      - name: Terraform FMT
        working-directory: task_1
        run: terraform fmt -check -recursive

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    if: github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381491972551:role/GithubActionsRole
          aws-region: us-east-1
      - name: Terraform INIT
        run: terraform init
        working-directory: task_1
        
      - name: Terraform PLAN
        run: terraform plan
        working-directory: task_1
        

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381491972551:role/GithubActionsRole
          aws-region: us-east-1
      - name: Terraform INIT
        run: terraform init
        working-directory: task_1

      - name: Terraform APPLY
        run: terraform apply -auto-approve
        working-directory: task_1
       